# Generated by Django 6.0.4 on 2026-04-11 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_initial_stock_alter_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='order',
            name='observation',
            field=models.TextField(blank=True, help_text='Notas o comparativa del admin', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code_entered',
            field=models.CharField(blank=True, help_text='Código que el cliente ingresó', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code_sent',
            field=models.CharField(blank=True, help_text='Código que enviamos al cliente', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
