# Generated by Django 6.0.4 on 2026-04-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_expires_at_order_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='otp_code_entered',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='otp_code_sent',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
