# Generated by Django 6.0.4 on 2026-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_features',
            field=models.TextField(blank=True, help_text='List of technical features', null=True),
        ),
    ]
